const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const INITIALIZE_CART = 'INITIALIZE_CART';
const FETCH_SLIDESHOW_PHOTOS_SUCCESS = 'FETCH_SLIDESHOW_PHOTOS_SUCCESS';
const FETCH_SLIDESHOW_PHOTOS_FAILURE = 'FETCH_SLIDESHOW_PHOTOS_FAILURE';

const MOVE_SLIDESHOW_SELECTIVELY = 'MOVE_SLIDESHOW_SELECTIVELY';
const MOVE_SLIDESHOW_FORWARD = 'MOVE_SLIDESHOW_FORWARD';
const MOVE_SLIDESHOW_BACKWARD = 'MOVE_SLIDESHOW_BACKWARD';

const CLICK_ON_PRODUCT_THUMB = 'CLICK_ON_PRODUCT_THUMB';
const SCROLL_PRODUCT_THUMBS_FORWARD = 'SCROLL_PRODUCT_THUMBS_FORWARD';
const SCROLL_PRODUCT_THUMBS_BACKWARD = 'SCROLL_PRODUCT_THUMBS_BACKWARD';
const TOGGLE_PRODUCT_GALLERY_MODAL = 'TOGGLE_PRODUCT_GALLERY_MODAL';

export {
  FETCH_PRODUCTS_REQUEST,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAILURE,
  ADD_PRODUCT_TO_CART,
  INITIALIZE_CART,
  FETCH_SLIDESHOW_PHOTOS_SUCCESS,
  FETCH_SLIDESHOW_PHOTOS_FAILURE,
  MOVE_SLIDESHOW_SELECTIVELY,
  MOVE_SLIDESHOW_FORWARD,
  MOVE_SLIDESHOW_BACKWARD,
  CLICK_ON_PRODUCT_THUMB,
  SCROLL_PRODUCT_THUMBS_FORWARD,
  SCROLL_PRODUCT_THUMBS_BACKWARD,
  TOGGLE_PRODUCT_GALLERY_MODAL
};
