export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INITIALIZE_CART = "INITIALIZE_CART";

export const FETCH_SLIDESHOW_PHOTOS_SUCCESS = "FETCH_SLIDESHOW_PHOTOS_SUCCESS";
export const FETCH_SLIDESHOW_PHOTOS_FAILURE = "FETCH_SLIDESHOW_PHOTOS_FAILURE";

export const CLICK_ON_PRODUCT_THUMB = "CLICK_ON_PRODUCT_THUMB";
export const SCROLL_PRODUCT_THUMBS_FORWARD = "SCROLL_PRODUCT_THUMBS_FORWARD";
export const SCROLL_PRODUCT_THUMBS_BACKWARD = "SCROLL_PRODUCT_THUMBS_BACKWARD";
export const TOGGLE_PRODUCT_GALLERY_MODAL = "TOGGLE_PRODUCT_GALLERY_MODAL";
