export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INITIALIZE_CART = "INITIALIZE_CART";

export const FETCH_SLIDESHOW_PHOTOS_REQUEST = "FETCH_SLIDESHOW_PHOTOS_REQUEST";
export const FETCH_SLIDESHOW_PHOTOS_SUCCESS = "FETCH_SLIDESHOW_PHOTOS_SUCCESS";
export const FETCH_SLIDESHOW_PHOTOS_FAILURE = "FETCH_SLIDESHOW_PHOTOS_FAILURE";

export const ORDER_PRODUCT_REQUEST = "ORDER_PRODUCT_REQUEST";
export const ORDER_PRODUCT_SUCCESS = "ORDER_PRODUCT_SUCCESS";
export const ORDER_PRODUCT_FAILURE = "ORDER_PRODUCT_FAILURE";
